export const CMD_MOVE_TO_CELL = 'moveTo'
export const CMD_SPAWN_NPC = 'spawnNPC'
export const CMD_REMOVE_NPC = 'removeNPC'
export const CMD_SPAWN_INGREDIENT = 'spawnIngredient'
export const CMD_REMOVE_INGREDIENT = 'removeIngredient'
export const CMD_ADD_TO_INVENTORY = 'addToInventory'
export const CMD_SET_WEATHER = 'setWeather'